[workspace]
members = [
    "crates/nylon-ring",
    "crates/nylon-ring-host",
    "examples/ex-nyring-host",
    "examples/ex-nyring-plugin",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/AssetsArt/nylon-ring"
homepage = "https://github.com/AssetsArt/nylon-ring"
readme = "README.md"
keywords = ["abi", "ffi", "plugin", "dynamic-loading", "hot-reload"]
categories = ["api-bindings", "development-tools::ffi"]

[workspace.dependencies]
nylon-ring = { version = "0.1.1", path = "crates/nylon-ring" }
tokio = { version = "1.48", default-features = false, features = ["sync", "time"] }
libloading = "0.9"
thiserror = "2"
dashmap = "6.1"
rustc-hash = "2.1"
criterion = { version = "0.8", features = ["html_reports"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
